backend:
  name: git-gateway
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "news"
    label: "News"
    folder: "content/news"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Breaking News", name: "breakingNews", widget: "boolean", default: false }
      - { label: "Categories", name: "newsCategories", widget: "list", default: ["General"] }
